INSERT INTO devinettes (question, reponse, indice, categorie, difficulte, points, is_premium, explication) VALUES
('Je suis grand et gris, j''ai une trompe, qui suis-je ?', 'éléphant', 'Je vis en Afrique et j''aime l''eau', 'Animaux', 'facile', 5, false, 'L''éléphant est le plus grand mammifère terrestre d''Afrique.'),
('Je tisse ma maison avec du fil, qui suis-je ?', 'araignée', 'Je mange les mouches', 'Animaux', 'facile', 5, false, 'L''araignée tisse sa toile pour capturer ses proies.'),
('Je coule sans jamais m''arrêter, qui suis-je ?', 'rivière', 'Les poissons nagent en moi', 'Nature', 'facile', 5, false, 'La rivière est un cours d''eau naturel.'),
('Je brille la nuit et éclaire le chemin, qui suis-je ?', 'lune', 'Je change de forme chaque nuit', 'Nature', 'facile', 5, false, NULL),
('Je suis roi de la savane, qui suis-je ?', 'lion', 'J''ai une crinière majestueuse', 'Animaux', 'facile', 5, false, NULL),
('Je donne de l''ombre au village, qui suis-je ?', 'baobab', 'Je suis un arbre sacré', 'Nature', 'facile', 8, false, NULL),
('Je raconte les histoires du village, qui suis-je ?', 'griot', 'Je joue de la musique', 'Culture', 'moyen', 10, false, 'Le griot est le gardien de la tradition orale en Afrique de l''Ouest.'),
('Plus je suis vieux, plus je suis respecté au village, qui suis-je ?', 'sage', 'J''ai beaucoup d''expérience', 'Culture', 'moyen', 10, false, NULL),
('Je nourris tout le village mais ne mange jamais, qui suis-je ?', 'mil', 'Je pousse dans les champs', 'Agriculture', 'moyen', 10, false, NULL),
('Je protège la maison mais n''ai pas de murs, qui suis-je ?', 'esprit', 'Les ancêtres veillent', 'Spiritualité', 'moyen', 12, false, NULL),
('Je lie les familles sans être vu, qui suis-je ?', 'totém', 'Chaque clan a le sien', 'Culture', 'difficile', 15, true, 'Le totém est l''animal protecteur d''un clan.'),
('Je parle sans voix, je enseigne sans école, qui suis-je ?', 'proverbe', 'La sagesse des anciens', 'Culture', 'difficile', 15, true, NULL),
('Je suis la richesse qui ne se compte pas, qui suis-je ?', 'honneur', 'Plus précieux que l''or', 'Valeurs', 'difficile', 18, true, NULL),
('Je unifie les villages sans être chef, qui suis-je ?', 'marché', 'Le lieu des échanges', 'Société', 'difficile', 15, true, NULL),
('Je guéris sans médicament, qui suis-je ?', 'parole', 'La force des mots justes', 'Spiritualité', 'difficile', 20, true, NULL),
('Je suis le premier et le dernier de chaque génération, qui suis-je ?', 'nom', 'Héritage ancestral', 'Généalogie', 'expert', 25, true, NULL),
('Je traverse les siècles sans vieillir, qui suis-je ?', 'tradition', 'Transmise de père en fils', 'Culture', 'expert', 25, true, NULL),
('Je suis invisible mais plus fort que le fer, qui suis-je ?', 'serment', 'Lien sacré entre hommes', 'Valeurs', 'expert', 30, true, NULL),
('Je nais de la terre mais appartiens au ciel, qui suis-je ?', 'ancêtre', 'Entre deux mondes', 'Spiritualité', 'expert', 30, true, NULL),
('Je suis le silence qui parle le plus fort, qui suis-je ?', 'respect', 'Vertu suprême', 'Valeurs', 'expert', 35, true, NULL),
('Je grandis en me cassant, qui suis-je ?', 'noix de karité', 'Trésor des femmes', 'Nature', 'moyen', 12, false, NULL),
('Je porte le village sur mon dos, qui suis-je ?', 'femme', 'Pilier de la famille', 'Société', 'difficile', 20, true, NULL),
('Je suis né d''argile mais je vis éternellement, qui suis-je ?', 'masque', 'Visage des esprits', 'Art', 'difficile', 18, true, NULL),
('Je rythme la vie sans jamais me tromper, qui suis-je ?', 'saison', 'Calendrier naturel', 'Nature', 'moyen', 10, false, NULL),
('Je suis la richesse du pauvre et la pauvreté du riche, qui suis-je ?', 'travail', 'Valeur universelle', 'Valeurs', 'difficile', 22, true, NULL);
