// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjpgnivxgbtfayiiuuqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqcGduaXZ4Z2J0ZmF5aWl1dXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyODE4NDYsImV4cCI6MjA2Nzg1Nzg0Nn0.AR5Az2z9UUsmZmzo1AB8p3dcWrC7yf7X-OM0zd_5iZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});